version: '3.4'

services:
  skybot.auth:
    image: ${DOCKER_REGISTRY}/skybot.auth
    build:
      context: .
      dockerfile: Skybot.Auth/Dockerfile
    ports:
      - "80"
    environment:
      - DOCKER_REGISTRY
      - IssuerUri
      - ApiClients__Texto.Func__ClientSecret
      - ApiClients__Skybot.Func__ClientSecret
      - StorageAccount__FileUri
      - StorageAccount__Key
      - StorageAccount__Name
      - Certificate__Filename
      - Certificate__Password